layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: crazymidnight
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  telegram: crazymidnigt
  # twitter: your_username
  # youtube: your_username
  instagram: _crazymidnight
  # unsplash: your_username
  vk: crazy_midnight
  # website: http://your_website_url

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: TensorFlow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/tensorflow/tensorflow.png
  
  - name: Keras
    web_url: https://github.com/topics/keras
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/keras/keras.png
  
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://avatars3.githubusercontent.com/u/31592135?s=280&v=4
 
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/rust/rust.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/go/go.png
    
  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/django/django.png
    
  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/flask/flask.png
